name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Set version from tag
      - name: Set version
        id: set-version
        run: |
          VERSION=${GITHUB_REF##*/}
          VERSION=${VERSION#v}
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      # Set repository name in lowercase
      - name: Set repository name
        id: set-repo-name
        run: |
          REPO_NAME=$(basename "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          OWNER_NAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
          echo "OWNER_NAME=$OWNER_NAME" >> $GITHUB_ENV

      # Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -f docker/Dockerfile \
            -t ghcr.io/$OWNER_NAME/$REPO_NAME:${VERSION} .
          docker push ghcr.io/$OWNER_NAME/$REPO_NAME:${VERSION}

          docker tag ghcr.io/$OWNER_NAME/$REPO_NAME:${VERSION} \
                     ghcr.io/$OWNER_NAME/$REPO_NAME:latest
          docker push ghcr.io/$OWNER_NAME/$REPO_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment:
      name: prod
      url: https://sync-mate-api-ws.zebaro.dev
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            REPO_NAME=$(basename "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
            OWNER_NAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')

            # Stop and remove old container
            docker stop $REPO_NAME || true
            docker rm $REPO_NAME || true

            # Remove old latest image if exists
            docker rmi ghcr.io/$OWNER_NAME/$REPO_NAME:latest || true

            # Pull new latest image
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/$OWNER_NAME/$REPO_NAME:latest

            # Run new container with restart
            docker run -d \
              --name $REPO_NAME \
              -p ${{ vars.DOCKER_PORT }}:8000 \
              --restart unless-stopped \
              ghcr.io/$OWNER_NAME/$REPO_NAME:latest
