name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache-deps.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Cache Poetry dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: '1.8.0'

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-ansi

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: '1.8.0'

      - name: Run linters
        run: |
          poetry run flake8 --max-line-length=120 app tests
          poetry run black --line-length 120 --check app tests
          poetry run isort --line-length 120 --check-only app tests

  test:
    needs: setup
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
      PROXIES_LIST: ${{ secrets.PROXIES_LIST }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: '1.8.0'

      - name: Run tests
        run: poetry run pytest
